# Generated by Django 2.1.5 on 2020-01-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_speciality_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submit',
            name='article',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
