# Generated by Django 2.1.5 on 2020-01-10 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0003_auto_20200110_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='user_sub',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
